import type { AgentDefinition } from './types'

export const BUILTIN_AGENT_DEFINITIONS = {
  blankText: {
    uid: 'body',
    name: 'Body writer',
    description: 'Blank text generation agent',
    category: 'starter',
    tags: ['starter', 'text'],
    systemPrompt: '',
    userPrompt: '',
    outputTarget: 'body',
    outputFormat: 'markdown',
    imageMode: null,
  },
  blankImage: {
    uid: 'image',
    name: 'Inline image',
    description: 'Generate an inline body image',
    category: 'starter',
    tags: ['starter', 'image'],
    systemPrompt: '',
    userPrompt: '',
    outputTarget: 'image',
    outputFormat: 'image',
    imageMode: 'generate',
  },
  blankStatic: {
    uid: 'note',
    name: 'Not included',
    description: 'Agent output saved for reference but not included in final post',
    category: 'starter',
    tags: ['starter', 'reference'],
    systemPrompt: '',
    userPrompt: '',
    outputTarget: 'none',
    outputFormat: 'markdown',
    imageMode: null,
  },
  staticImage: {
    uid: 'static_image',
    name: 'Static image',
    description: 'Select an existing image for the final body',
    category: 'starter',
    tags: ['starter', 'image'],
    systemPrompt: '',
    userPrompt: '',
    outputTarget: 'body',
    outputFormat: 'static',
    imageMode: 'selected',
  },
} satisfies Record<string, AgentDefinition>
